#!/bin/bash
set -eou pipefail
script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
set -a; source "${script_dir}/.env.default"; set +a

which ! awscli &>/dev/null && echo "awscli is not installed" && exit 1

aws eks update-kubeconfig --region "${AWS_REGION}" --name "${EKS_CLUSTER}"
