#!/bin/bash
set -eou pipefail
script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
set -a; source "${script_dir}/.env.default"; set +a

which ! awscli &>/dev/null && echo "awscli is not installed" && exit 1
which ! eksctl &>/dev/null && echo "eksctl is not installed" && exit 1

eksctl create cluster --name "${EKS_CLUSTER}" --region "${AWS_REGION}" --node-type t2.micro --nodes 2 --nodes-max 3 --nodes-min 1
