#!/bin/bash
set -eou pipefail

shopt -s expand_aliases
if [[ "${OSTYPE}" == "darwin"* ]]; then
    if ! which buf &>/dev/null; then brew install buf; fi
else
    alias buf="docker run --volume $(pwd):/workspace --workdir /workspace bufbuild/buf"
fi

buf generate
